######################################################################
##
## Filename: SDRAM_top.udo
## Created on: Sun Sep 17 18:31:38 中国标准时间 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
