######################################################################
##
## Filename: SDRAM_CTRL_TOP.udo
## Created on: Wed Sep 13 20:03:06 中国标准时间 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
