######################################################################
##
## Filename: tb_top_sdram.udo
## Created on: Wed Sep 13 19:59:40 中国标准时间 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
